In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a=[[1,5,8],[9,3,6]]
a

[[1, 5, 8], [9, 3, 6]]

In [5]:
b=np.array(a)
b

array([[1, 5, 8],
       [9, 3, 6]])

In [6]:
type(b)

numpy.ndarray

In [7]:
b.shape

(2, 3)

In [8]:
L1= list(range(100000))
L2= list(range(100000))

In [9]:
A1=np.arange(100000)
A2=np.arange(100000)

In [10]:
import time
start = time.time()
L3=list(map(lambda x,y:x+y,L1,L2))
end= time.time()
print((end-start)*1000) # time differnce
print(f'time taken is {((end-start)*1000)} millisecond')

20.155668258666992
time taken is 20.155668258666992 millisecond


In [11]:
import time
start = time.time()
A3=A1+A2
end= time.time()
print((end-start)*1000) # time differnce
print(f'time taken is {((end-start)*1000)} millisecond')

1.972198486328125
time taken is 1.972198486328125 millisecond


In [12]:
a=np.array([[1,5,6],
           [8,9,5],
           [2,6,6]])
print(a)
print(a.shape)
print(a.size)
a[1,1]
a[2,0]


[[1 5 6]
 [8 9 5]
 [2 6 6]]
(3, 3)
9


2

In [13]:
a[1:,1:]

array([[9, 5],
       [6, 6]])

In [14]:
a[1:,:2]

array([[8, 9],
       [2, 6]])

In [15]:
b=np.array([[2,5,8],[5,6,-3],[8,9,6]])
print(b)
print(a)

[[ 2  5  8]
 [ 5  6 -3]
 [ 8  9  6]]
[[1 5 6]
 [8 9 5]
 [2 6 6]]


In [16]:
print('a+b')
print(a+b)
print('or') 
print(np.add(a,b))
print()
print('a*b')
print(a*b)

a+b
[[ 3 10 14]
 [13 15  2]
 [10 15 12]]
or
[[ 3 10 14]
 [13 15  2]
 [10 15 12]]

a*b
[[  2  25  48]
 [ 40  54 -15]
 [ 16  54  36]]


In [17]:
np.mean(a,axis=0) #axis : 0= column
np.mean(a,axis=1) #axis : 1= row

array([4.        , 7.33333333, 4.66666667])

In [18]:
np.var(a) # variance

5.777777777777778

In [26]:
np.cumsum(a,axis=1)

array([[ 1,  6, 12],
       [ 8, 17, 22],
       [ 2,  8, 14]])

In [29]:
np.argmax(a)

4